[pytest]
# Let the tests import your app ("from app import create_app") as if they
# were run from the project's main folder.
pythonpath = .
# Look for tests only in the tests/ folder.
testpaths = tests