"""Add livestock, weight and health tables

Revision ID: b10c03435170
Revises: 084ff8ad82b9
Create Date: 2026-10-08 07:42:29.215925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10c03435170'
down_revision = '084ff8ad82b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livestock',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.Enum('CATTLE', 'CHICKEN', 'GOAT', 'SHEEP', name='species_enum'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender_enum'), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ),
    sa.PrimaryKeyConstraint('animal_id')
    )
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_livestock_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('health_records',
    sa.Column('h_record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.Enum('ILLNESS', 'VACCINATION', 'TREATMENT', 'CHECKUP', name='health_record_type_enum'), nullable=False),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('treatment', sa.String(length=100), nullable=True),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('h_record_id')
    )
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_records_animal_id'), ['animal_id'], unique=False)

    op.create_table('weight_records',
    sa.Column('w_record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.CheckConstraint('weight > 0', name='ck_weight_positive'),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('w_record_id')
    )
    with op.batch_alter_table('weight_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_records_animal_id'), ['animal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_records_animal_id'))

    op.drop_table('weight_records')
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_records_animal_id'))

    op.drop_table('health_records')
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_livestock_farmer_id'))

    op.drop_table('livestock')
    # ### end Alembic commands ###
    
    # PostgreSQL stores each Enum as a separate named type that outlives its
    # table. Drop them too, or running upgrade again fails with "already exists".
    sa.Enum(name="health_record_type_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="gender_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="species_enum").drop(op.get_bind(), checkfirst=True)
