"""Add breeding, production, commercial and mortality tables

Revision ID: e5abbd817248
Revises: b10c03435170
Create Date: 2026-10-08 08:24:58.106389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5abbd817248'
down_revision = 'b10c03435170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeding_record',
    sa.Column('b_record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('sire_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('EXPECTANT', 'SUCCESSFUL BIRTH', 'NO BIRTH', name='breeding_status_enum'), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('num_stillborn', sa.Integer(), nullable=False),
    sa.CheckConstraint('num_stillborn >= 0', name='ck_stillborn_not_negative'),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('b_record_id')
    )
    with op.batch_alter_table('breeding_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeding_record_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_record_sire_id'), ['sire_id'], unique=False)

    op.create_table('commercial_info',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transaction_type_enum'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('other_party', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_amount_not_negative'),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('commercial_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commercial_info_animal_id'), ['animal_id'], unique=False)

    op.create_table('mortality_records',
    sa.Column('m_record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=False),
    sa.Column('age_at_death', sa.Integer(), nullable=True),
    sa.Column('cause_of_death', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('m_record_id'),
    sa.UniqueConstraint('animal_id')
    )
    op.create_table('production_data',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('yield', sa.Float(), nullable=False),
    sa.Column('metric', sa.String(length=10), nullable=False),
    sa.CheckConstraint('"yield" >= 0', name='ck_yield_not_negative'),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('production_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_data_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_record_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_livestock_birth_event', 'breeding_record', ['b_record_id'], ['b_record_id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.drop_constraint('fk_livestock_birth_event', type_='foreignkey')
        batch_op.drop_column('b_record_id')

    with op.batch_alter_table('production_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_data_animal_id'))

    op.drop_table('production_data')
    op.drop_table('mortality_records')
    with op.batch_alter_table('commercial_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commercial_info_animal_id'))

    op.drop_table('commercial_info')
    with op.batch_alter_table('breeding_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_record_sire_id'))
        batch_op.drop_index(batch_op.f('ix_breeding_record_animal_id'))

    op.drop_table('breeding_record')
    # ### end Alembic commands ###
    
    # PostgreSQL stores each Enum as a separate named type that outlives its
    # table. Drop them too, or running upgrade again fails with "already exists".
    sa.Enum(name="transaction_type_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="breeding_status_enum").drop(op.get_bind(), checkfirst=True)
